// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserInfoRecordProto.proto

#ifndef PROTOBUF_UserInfoRecordProto_2eproto__INCLUDED
#define PROTOBUF_UserInfoRecordProto_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_UserInfoRecordProto_2eproto();
void protobuf_AssignDesc_UserInfoRecordProto_2eproto();
void protobuf_ShutdownFile_UserInfoRecordProto_2eproto();

class BaseAttrProto;
class UserInfoRecordProto;

enum BaseAttrProto_ePart {
  BaseAttrProto_ePart_kPart_Null = 0,
  BaseAttrProto_ePart_kPart_Fighter = 1,
  BaseAttrProto_ePart_kPart_Armor = 2,
  BaseAttrProto_ePart_kPart_Wingman = 3,
  BaseAttrProto_ePart_kPart_Attache = 4
};
bool BaseAttrProto_ePart_IsValid(int value);
const BaseAttrProto_ePart BaseAttrProto_ePart_ePart_MIN = BaseAttrProto_ePart_kPart_Null;
const BaseAttrProto_ePart BaseAttrProto_ePart_ePart_MAX = BaseAttrProto_ePart_kPart_Attache;
const int BaseAttrProto_ePart_ePart_ARRAYSIZE = BaseAttrProto_ePart_ePart_MAX + 1;

const ::google::protobuf::EnumDescriptor* BaseAttrProto_ePart_descriptor();
inline const ::std::string& BaseAttrProto_ePart_Name(BaseAttrProto_ePart value) {
  return ::google::protobuf::internal::NameOfEnum(
    BaseAttrProto_ePart_descriptor(), value);
}
inline bool BaseAttrProto_ePart_Parse(
    const ::std::string& name, BaseAttrProto_ePart* value) {
  return ::google::protobuf::internal::ParseNamedEnum<BaseAttrProto_ePart>(
    BaseAttrProto_ePart_descriptor(), name, value);
}
enum BaseAttrProto_eQuality {
  BaseAttrProto_eQuality_kQuality_Gray = 0,
  BaseAttrProto_eQuality_kQuality_White = 1,
  BaseAttrProto_eQuality_kQuality_Green = 2,
  BaseAttrProto_eQuality_kQuality_Blue = 3,
  BaseAttrProto_eQuality_kQuality_Purple = 4,
  BaseAttrProto_eQuality_kQuality_Orange = 5
};
bool BaseAttrProto_eQuality_IsValid(int value);
const BaseAttrProto_eQuality BaseAttrProto_eQuality_eQuality_MIN = BaseAttrProto_eQuality_kQuality_Gray;
const BaseAttrProto_eQuality BaseAttrProto_eQuality_eQuality_MAX = BaseAttrProto_eQuality_kQuality_Orange;
const int BaseAttrProto_eQuality_eQuality_ARRAYSIZE = BaseAttrProto_eQuality_eQuality_MAX + 1;

const ::google::protobuf::EnumDescriptor* BaseAttrProto_eQuality_descriptor();
inline const ::std::string& BaseAttrProto_eQuality_Name(BaseAttrProto_eQuality value) {
  return ::google::protobuf::internal::NameOfEnum(
    BaseAttrProto_eQuality_descriptor(), value);
}
inline bool BaseAttrProto_eQuality_Parse(
    const ::std::string& name, BaseAttrProto_eQuality* value) {
  return ::google::protobuf::internal::ParseNamedEnum<BaseAttrProto_eQuality>(
    BaseAttrProto_eQuality_descriptor(), name, value);
}
enum BaseAttrProto_eQualityRank {
  BaseAttrProto_eQualityRank_kQuaRank_0 = 0,
  BaseAttrProto_eQualityRank_kQuaRank_1 = 1,
  BaseAttrProto_eQualityRank_kQuaRank_2 = 2,
  BaseAttrProto_eQualityRank_kQuaRank_Max = 3,
  BaseAttrProto_eQualityRank_kQuaRank_Gold = 4
};
bool BaseAttrProto_eQualityRank_IsValid(int value);
const BaseAttrProto_eQualityRank BaseAttrProto_eQualityRank_eQualityRank_MIN = BaseAttrProto_eQualityRank_kQuaRank_0;
const BaseAttrProto_eQualityRank BaseAttrProto_eQualityRank_eQualityRank_MAX = BaseAttrProto_eQualityRank_kQuaRank_Gold;
const int BaseAttrProto_eQualityRank_eQualityRank_ARRAYSIZE = BaseAttrProto_eQualityRank_eQualityRank_MAX + 1;

const ::google::protobuf::EnumDescriptor* BaseAttrProto_eQualityRank_descriptor();
inline const ::std::string& BaseAttrProto_eQualityRank_Name(BaseAttrProto_eQualityRank value) {
  return ::google::protobuf::internal::NameOfEnum(
    BaseAttrProto_eQualityRank_descriptor(), value);
}
inline bool BaseAttrProto_eQualityRank_Parse(
    const ::std::string& name, BaseAttrProto_eQualityRank* value) {
  return ::google::protobuf::internal::ParseNamedEnum<BaseAttrProto_eQualityRank>(
    BaseAttrProto_eQualityRank_descriptor(), name, value);
}
// ===================================================================

class BaseAttrProto : public ::google::protobuf::Message {
 public:
  BaseAttrProto();
  virtual ~BaseAttrProto();

  BaseAttrProto(const BaseAttrProto& from);

  inline BaseAttrProto& operator=(const BaseAttrProto& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BaseAttrProto& default_instance();

  void Swap(BaseAttrProto* other);

  // implements Message ----------------------------------------------

  BaseAttrProto* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const BaseAttrProto& from);
  void MergeFrom(const BaseAttrProto& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef BaseAttrProto_ePart ePart;
  static const ePart kPart_Null = BaseAttrProto_ePart_kPart_Null;
  static const ePart kPart_Fighter = BaseAttrProto_ePart_kPart_Fighter;
  static const ePart kPart_Armor = BaseAttrProto_ePart_kPart_Armor;
  static const ePart kPart_Wingman = BaseAttrProto_ePart_kPart_Wingman;
  static const ePart kPart_Attache = BaseAttrProto_ePart_kPart_Attache;
  static inline bool ePart_IsValid(int value) {
    return BaseAttrProto_ePart_IsValid(value);
  }
  static const ePart ePart_MIN =
    BaseAttrProto_ePart_ePart_MIN;
  static const ePart ePart_MAX =
    BaseAttrProto_ePart_ePart_MAX;
  static const int ePart_ARRAYSIZE =
    BaseAttrProto_ePart_ePart_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  ePart_descriptor() {
    return BaseAttrProto_ePart_descriptor();
  }
  static inline const ::std::string& ePart_Name(ePart value) {
    return BaseAttrProto_ePart_Name(value);
  }
  static inline bool ePart_Parse(const ::std::string& name,
      ePart* value) {
    return BaseAttrProto_ePart_Parse(name, value);
  }

  typedef BaseAttrProto_eQuality eQuality;
  static const eQuality kQuality_Gray = BaseAttrProto_eQuality_kQuality_Gray;
  static const eQuality kQuality_White = BaseAttrProto_eQuality_kQuality_White;
  static const eQuality kQuality_Green = BaseAttrProto_eQuality_kQuality_Green;
  static const eQuality kQuality_Blue = BaseAttrProto_eQuality_kQuality_Blue;
  static const eQuality kQuality_Purple = BaseAttrProto_eQuality_kQuality_Purple;
  static const eQuality kQuality_Orange = BaseAttrProto_eQuality_kQuality_Orange;
  static inline bool eQuality_IsValid(int value) {
    return BaseAttrProto_eQuality_IsValid(value);
  }
  static const eQuality eQuality_MIN =
    BaseAttrProto_eQuality_eQuality_MIN;
  static const eQuality eQuality_MAX =
    BaseAttrProto_eQuality_eQuality_MAX;
  static const int eQuality_ARRAYSIZE =
    BaseAttrProto_eQuality_eQuality_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  eQuality_descriptor() {
    return BaseAttrProto_eQuality_descriptor();
  }
  static inline const ::std::string& eQuality_Name(eQuality value) {
    return BaseAttrProto_eQuality_Name(value);
  }
  static inline bool eQuality_Parse(const ::std::string& name,
      eQuality* value) {
    return BaseAttrProto_eQuality_Parse(name, value);
  }

  typedef BaseAttrProto_eQualityRank eQualityRank;
  static const eQualityRank kQuaRank_0 = BaseAttrProto_eQualityRank_kQuaRank_0;
  static const eQualityRank kQuaRank_1 = BaseAttrProto_eQualityRank_kQuaRank_1;
  static const eQualityRank kQuaRank_2 = BaseAttrProto_eQualityRank_kQuaRank_2;
  static const eQualityRank kQuaRank_Max = BaseAttrProto_eQualityRank_kQuaRank_Max;
  static const eQualityRank kQuaRank_Gold = BaseAttrProto_eQualityRank_kQuaRank_Gold;
  static inline bool eQualityRank_IsValid(int value) {
    return BaseAttrProto_eQualityRank_IsValid(value);
  }
  static const eQualityRank eQualityRank_MIN =
    BaseAttrProto_eQualityRank_eQualityRank_MIN;
  static const eQualityRank eQualityRank_MAX =
    BaseAttrProto_eQualityRank_eQualityRank_MAX;
  static const int eQualityRank_ARRAYSIZE =
    BaseAttrProto_eQualityRank_eQualityRank_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  eQualityRank_descriptor() {
    return BaseAttrProto_eQualityRank_descriptor();
  }
  static inline const ::std::string& eQualityRank_Name(eQualityRank value) {
    return BaseAttrProto_eQualityRank_Name(value);
  }
  static inline bool eQualityRank_Parse(const ::std::string& name,
      eQualityRank* value) {
    return BaseAttrProto_eQualityRank_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // required int32 sid = 1 [default = 0];
  inline bool has_sid() const;
  inline void clear_sid();
  static const int kSidFieldNumber = 1;
  inline ::google::protobuf::int32 sid() const;
  inline void set_sid(::google::protobuf::int32 value);

  // required int32 eid = 2 [default = 0];
  inline bool has_eid() const;
  inline void clear_eid();
  static const int kEidFieldNumber = 2;
  inline ::google::protobuf::int32 eid() const;
  inline void set_eid(::google::protobuf::int32 value);

  // required .BaseAttrProto.ePart part = 3 [default = kPart_Null];
  inline bool has_part() const;
  inline void clear_part();
  static const int kPartFieldNumber = 3;
  inline ::BaseAttrProto_ePart part() const;
  inline void set_part(::BaseAttrProto_ePart value);

  // required int32 level = 4 [default = 1];
  inline bool has_level() const;
  inline void clear_level();
  static const int kLevelFieldNumber = 4;
  inline ::google::protobuf::int32 level() const;
  inline void set_level(::google::protobuf::int32 value);

  // required .BaseAttrProto.eQuality quality = 5 [default = kQuality_White];
  inline bool has_quality() const;
  inline void clear_quality();
  static const int kQualityFieldNumber = 5;
  inline ::BaseAttrProto_eQuality quality() const;
  inline void set_quality(::BaseAttrProto_eQuality value);

  // required .BaseAttrProto.eQualityRank quaRank = 6 [default = kQuaRank_0];
  inline bool has_quarank() const;
  inline void clear_quarank();
  static const int kQuaRankFieldNumber = 6;
  inline ::BaseAttrProto_eQualityRank quarank() const;
  inline void set_quarank(::BaseAttrProto_eQualityRank value);

  // optional int32 hp = 7;
  inline bool has_hp() const;
  inline void clear_hp();
  static const int kHpFieldNumber = 7;
  inline ::google::protobuf::int32 hp() const;
  inline void set_hp(::google::protobuf::int32 value);

  // optional int32 defence = 8;
  inline bool has_defence() const;
  inline void clear_defence();
  static const int kDefenceFieldNumber = 8;
  inline ::google::protobuf::int32 defence() const;
  inline void set_defence(::google::protobuf::int32 value);

  // optional int32 atk = 9;
  inline bool has_atk() const;
  inline void clear_atk();
  static const int kAtkFieldNumber = 9;
  inline ::google::protobuf::int32 atk() const;
  inline void set_atk(::google::protobuf::int32 value);

  // optional int32 atkSpeed = 10;
  inline bool has_atkspeed() const;
  inline void clear_atkspeed();
  static const int kAtkSpeedFieldNumber = 10;
  inline ::google::protobuf::int32 atkspeed() const;
  inline void set_atkspeed(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:BaseAttrProto)
 private:
  inline void set_has_sid();
  inline void clear_has_sid();
  inline void set_has_eid();
  inline void clear_has_eid();
  inline void set_has_part();
  inline void clear_has_part();
  inline void set_has_level();
  inline void clear_has_level();
  inline void set_has_quality();
  inline void clear_has_quality();
  inline void set_has_quarank();
  inline void clear_has_quarank();
  inline void set_has_hp();
  inline void clear_has_hp();
  inline void set_has_defence();
  inline void clear_has_defence();
  inline void set_has_atk();
  inline void clear_has_atk();
  inline void set_has_atkspeed();
  inline void clear_has_atkspeed();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 sid_;
  ::google::protobuf::int32 eid_;
  int part_;
  ::google::protobuf::int32 level_;
  int quality_;
  int quarank_;
  ::google::protobuf::int32 hp_;
  ::google::protobuf::int32 defence_;
  ::google::protobuf::int32 atk_;
  ::google::protobuf::int32 atkspeed_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(10 + 31) / 32];

  friend void  protobuf_AddDesc_UserInfoRecordProto_2eproto();
  friend void protobuf_AssignDesc_UserInfoRecordProto_2eproto();
  friend void protobuf_ShutdownFile_UserInfoRecordProto_2eproto();

  void InitAsDefaultInstance();
  static BaseAttrProto* default_instance_;
};
// -------------------------------------------------------------------

class UserInfoRecordProto : public ::google::protobuf::Message {
 public:
  UserInfoRecordProto();
  virtual ~UserInfoRecordProto();

  UserInfoRecordProto(const UserInfoRecordProto& from);

  inline UserInfoRecordProto& operator=(const UserInfoRecordProto& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UserInfoRecordProto& default_instance();

  void Swap(UserInfoRecordProto* other);

  // implements Message ----------------------------------------------

  UserInfoRecordProto* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UserInfoRecordProto& from);
  void MergeFrom(const UserInfoRecordProto& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 userID = 1 [default = 0];
  inline bool has_userid() const;
  inline void clear_userid();
  static const int kUserIDFieldNumber = 1;
  inline ::google::protobuf::int32 userid() const;
  inline void set_userid(::google::protobuf::int32 value);

  // required string userName = 2 [default = "T"];
  inline bool has_username() const;
  inline void clear_username();
  static const int kUserNameFieldNumber = 2;
  inline const ::std::string& username() const;
  inline void set_username(const ::std::string& value);
  inline void set_username(const char* value);
  inline void set_username(const char* value, size_t size);
  inline ::std::string* mutable_username();
  inline ::std::string* release_username();
  inline void set_allocated_username(::std::string* username);

  // required int32 currentFighterID = 3 [default = 0];
  inline bool has_currentfighterid() const;
  inline void clear_currentfighterid();
  static const int kCurrentFighterIDFieldNumber = 3;
  inline ::google::protobuf::int32 currentfighterid() const;
  inline void set_currentfighterid(::google::protobuf::int32 value);

  // repeated string testName = 5;
  inline int testname_size() const;
  inline void clear_testname();
  static const int kTestNameFieldNumber = 5;
  inline const ::std::string& testname(int index) const;
  inline ::std::string* mutable_testname(int index);
  inline void set_testname(int index, const ::std::string& value);
  inline void set_testname(int index, const char* value);
  inline void set_testname(int index, const char* value, size_t size);
  inline ::std::string* add_testname();
  inline void add_testname(const ::std::string& value);
  inline void add_testname(const char* value);
  inline void add_testname(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& testname() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_testname();

  // repeated .BaseAttrProto unitAttr = 4;
  inline int unitattr_size() const;
  inline void clear_unitattr();
  static const int kUnitAttrFieldNumber = 4;
  inline const ::BaseAttrProto& unitattr(int index) const;
  inline ::BaseAttrProto* mutable_unitattr(int index);
  inline ::BaseAttrProto* add_unitattr();
  inline const ::google::protobuf::RepeatedPtrField< ::BaseAttrProto >&
      unitattr() const;
  inline ::google::protobuf::RepeatedPtrField< ::BaseAttrProto >*
      mutable_unitattr();

  // @@protoc_insertion_point(class_scope:UserInfoRecordProto)
 private:
  inline void set_has_userid();
  inline void clear_has_userid();
  inline void set_has_username();
  inline void clear_has_username();
  inline void set_has_currentfighterid();
  inline void clear_has_currentfighterid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* username_;
  static ::std::string* _default_username_;
  ::google::protobuf::int32 userid_;
  ::google::protobuf::int32 currentfighterid_;
  ::google::protobuf::RepeatedPtrField< ::std::string> testname_;
  ::google::protobuf::RepeatedPtrField< ::BaseAttrProto > unitattr_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];

  friend void  protobuf_AddDesc_UserInfoRecordProto_2eproto();
  friend void protobuf_AssignDesc_UserInfoRecordProto_2eproto();
  friend void protobuf_ShutdownFile_UserInfoRecordProto_2eproto();

  void InitAsDefaultInstance();
  static UserInfoRecordProto* default_instance_;
};
// ===================================================================


// ===================================================================

// BaseAttrProto

// required int32 sid = 1 [default = 0];
inline bool BaseAttrProto::has_sid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BaseAttrProto::set_has_sid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void BaseAttrProto::clear_has_sid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void BaseAttrProto::clear_sid() {
  sid_ = 0;
  clear_has_sid();
}
inline ::google::protobuf::int32 BaseAttrProto::sid() const {
  return sid_;
}
inline void BaseAttrProto::set_sid(::google::protobuf::int32 value) {
  set_has_sid();
  sid_ = value;
}

// required int32 eid = 2 [default = 0];
inline bool BaseAttrProto::has_eid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void BaseAttrProto::set_has_eid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void BaseAttrProto::clear_has_eid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void BaseAttrProto::clear_eid() {
  eid_ = 0;
  clear_has_eid();
}
inline ::google::protobuf::int32 BaseAttrProto::eid() const {
  return eid_;
}
inline void BaseAttrProto::set_eid(::google::protobuf::int32 value) {
  set_has_eid();
  eid_ = value;
}

// required .BaseAttrProto.ePart part = 3 [default = kPart_Null];
inline bool BaseAttrProto::has_part() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void BaseAttrProto::set_has_part() {
  _has_bits_[0] |= 0x00000004u;
}
inline void BaseAttrProto::clear_has_part() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void BaseAttrProto::clear_part() {
  part_ = 0;
  clear_has_part();
}
inline ::BaseAttrProto_ePart BaseAttrProto::part() const {
  return static_cast< ::BaseAttrProto_ePart >(part_);
}
inline void BaseAttrProto::set_part(::BaseAttrProto_ePart value) {
  assert(::BaseAttrProto_ePart_IsValid(value));
  set_has_part();
  part_ = value;
}

// required int32 level = 4 [default = 1];
inline bool BaseAttrProto::has_level() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void BaseAttrProto::set_has_level() {
  _has_bits_[0] |= 0x00000008u;
}
inline void BaseAttrProto::clear_has_level() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void BaseAttrProto::clear_level() {
  level_ = 1;
  clear_has_level();
}
inline ::google::protobuf::int32 BaseAttrProto::level() const {
  return level_;
}
inline void BaseAttrProto::set_level(::google::protobuf::int32 value) {
  set_has_level();
  level_ = value;
}

// required .BaseAttrProto.eQuality quality = 5 [default = kQuality_White];
inline bool BaseAttrProto::has_quality() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void BaseAttrProto::set_has_quality() {
  _has_bits_[0] |= 0x00000010u;
}
inline void BaseAttrProto::clear_has_quality() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void BaseAttrProto::clear_quality() {
  quality_ = 1;
  clear_has_quality();
}
inline ::BaseAttrProto_eQuality BaseAttrProto::quality() const {
  return static_cast< ::BaseAttrProto_eQuality >(quality_);
}
inline void BaseAttrProto::set_quality(::BaseAttrProto_eQuality value) {
  assert(::BaseAttrProto_eQuality_IsValid(value));
  set_has_quality();
  quality_ = value;
}

// required .BaseAttrProto.eQualityRank quaRank = 6 [default = kQuaRank_0];
inline bool BaseAttrProto::has_quarank() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void BaseAttrProto::set_has_quarank() {
  _has_bits_[0] |= 0x00000020u;
}
inline void BaseAttrProto::clear_has_quarank() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void BaseAttrProto::clear_quarank() {
  quarank_ = 0;
  clear_has_quarank();
}
inline ::BaseAttrProto_eQualityRank BaseAttrProto::quarank() const {
  return static_cast< ::BaseAttrProto_eQualityRank >(quarank_);
}
inline void BaseAttrProto::set_quarank(::BaseAttrProto_eQualityRank value) {
  assert(::BaseAttrProto_eQualityRank_IsValid(value));
  set_has_quarank();
  quarank_ = value;
}

// optional int32 hp = 7;
inline bool BaseAttrProto::has_hp() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void BaseAttrProto::set_has_hp() {
  _has_bits_[0] |= 0x00000040u;
}
inline void BaseAttrProto::clear_has_hp() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void BaseAttrProto::clear_hp() {
  hp_ = 0;
  clear_has_hp();
}
inline ::google::protobuf::int32 BaseAttrProto::hp() const {
  return hp_;
}
inline void BaseAttrProto::set_hp(::google::protobuf::int32 value) {
  set_has_hp();
  hp_ = value;
}

// optional int32 defence = 8;
inline bool BaseAttrProto::has_defence() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void BaseAttrProto::set_has_defence() {
  _has_bits_[0] |= 0x00000080u;
}
inline void BaseAttrProto::clear_has_defence() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void BaseAttrProto::clear_defence() {
  defence_ = 0;
  clear_has_defence();
}
inline ::google::protobuf::int32 BaseAttrProto::defence() const {
  return defence_;
}
inline void BaseAttrProto::set_defence(::google::protobuf::int32 value) {
  set_has_defence();
  defence_ = value;
}

// optional int32 atk = 9;
inline bool BaseAttrProto::has_atk() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void BaseAttrProto::set_has_atk() {
  _has_bits_[0] |= 0x00000100u;
}
inline void BaseAttrProto::clear_has_atk() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void BaseAttrProto::clear_atk() {
  atk_ = 0;
  clear_has_atk();
}
inline ::google::protobuf::int32 BaseAttrProto::atk() const {
  return atk_;
}
inline void BaseAttrProto::set_atk(::google::protobuf::int32 value) {
  set_has_atk();
  atk_ = value;
}

// optional int32 atkSpeed = 10;
inline bool BaseAttrProto::has_atkspeed() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void BaseAttrProto::set_has_atkspeed() {
  _has_bits_[0] |= 0x00000200u;
}
inline void BaseAttrProto::clear_has_atkspeed() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void BaseAttrProto::clear_atkspeed() {
  atkspeed_ = 0;
  clear_has_atkspeed();
}
inline ::google::protobuf::int32 BaseAttrProto::atkspeed() const {
  return atkspeed_;
}
inline void BaseAttrProto::set_atkspeed(::google::protobuf::int32 value) {
  set_has_atkspeed();
  atkspeed_ = value;
}

// -------------------------------------------------------------------

// UserInfoRecordProto

// required int32 userID = 1 [default = 0];
inline bool UserInfoRecordProto::has_userid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UserInfoRecordProto::set_has_userid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UserInfoRecordProto::clear_has_userid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UserInfoRecordProto::clear_userid() {
  userid_ = 0;
  clear_has_userid();
}
inline ::google::protobuf::int32 UserInfoRecordProto::userid() const {
  return userid_;
}
inline void UserInfoRecordProto::set_userid(::google::protobuf::int32 value) {
  set_has_userid();
  userid_ = value;
}

// required string userName = 2 [default = "T"];
inline bool UserInfoRecordProto::has_username() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void UserInfoRecordProto::set_has_username() {
  _has_bits_[0] |= 0x00000002u;
}
inline void UserInfoRecordProto::clear_has_username() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void UserInfoRecordProto::clear_username() {
  if (username_ != _default_username_) {
    username_->assign(*_default_username_);
  }
  clear_has_username();
}
inline const ::std::string& UserInfoRecordProto::username() const {
  return *username_;
}
inline void UserInfoRecordProto::set_username(const ::std::string& value) {
  set_has_username();
  if (username_ == _default_username_) {
    username_ = new ::std::string;
  }
  username_->assign(value);
}
inline void UserInfoRecordProto::set_username(const char* value) {
  set_has_username();
  if (username_ == _default_username_) {
    username_ = new ::std::string;
  }
  username_->assign(value);
}
inline void UserInfoRecordProto::set_username(const char* value, size_t size) {
  set_has_username();
  if (username_ == _default_username_) {
    username_ = new ::std::string;
  }
  username_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* UserInfoRecordProto::mutable_username() {
  set_has_username();
  if (username_ == _default_username_) {
    username_ = new ::std::string(*_default_username_);
  }
  return username_;
}
inline ::std::string* UserInfoRecordProto::release_username() {
  clear_has_username();
  if (username_ == _default_username_) {
    return NULL;
  } else {
    ::std::string* temp = username_;
    username_ = const_cast< ::std::string*>(_default_username_);
    return temp;
  }
}
inline void UserInfoRecordProto::set_allocated_username(::std::string* username) {
  if (username_ != _default_username_) {
    delete username_;
  }
  if (username) {
    set_has_username();
    username_ = username;
  } else {
    clear_has_username();
    username_ = const_cast< ::std::string*>(_default_username_);
  }
}

// required int32 currentFighterID = 3 [default = 0];
inline bool UserInfoRecordProto::has_currentfighterid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void UserInfoRecordProto::set_has_currentfighterid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void UserInfoRecordProto::clear_has_currentfighterid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void UserInfoRecordProto::clear_currentfighterid() {
  currentfighterid_ = 0;
  clear_has_currentfighterid();
}
inline ::google::protobuf::int32 UserInfoRecordProto::currentfighterid() const {
  return currentfighterid_;
}
inline void UserInfoRecordProto::set_currentfighterid(::google::protobuf::int32 value) {
  set_has_currentfighterid();
  currentfighterid_ = value;
}

// repeated string testName = 5;
inline int UserInfoRecordProto::testname_size() const {
  return testname_.size();
}
inline void UserInfoRecordProto::clear_testname() {
  testname_.Clear();
}
inline const ::std::string& UserInfoRecordProto::testname(int index) const {
  return testname_.Get(index);
}
inline ::std::string* UserInfoRecordProto::mutable_testname(int index) {
  return testname_.Mutable(index);
}
inline void UserInfoRecordProto::set_testname(int index, const ::std::string& value) {
  testname_.Mutable(index)->assign(value);
}
inline void UserInfoRecordProto::set_testname(int index, const char* value) {
  testname_.Mutable(index)->assign(value);
}
inline void UserInfoRecordProto::set_testname(int index, const char* value, size_t size) {
  testname_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline ::std::string* UserInfoRecordProto::add_testname() {
  return testname_.Add();
}
inline void UserInfoRecordProto::add_testname(const ::std::string& value) {
  testname_.Add()->assign(value);
}
inline void UserInfoRecordProto::add_testname(const char* value) {
  testname_.Add()->assign(value);
}
inline void UserInfoRecordProto::add_testname(const char* value, size_t size) {
  testname_.Add()->assign(reinterpret_cast<const char*>(value), size);
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
UserInfoRecordProto::testname() const {
  return testname_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
UserInfoRecordProto::mutable_testname() {
  return &testname_;
}

// repeated .BaseAttrProto unitAttr = 4;
inline int UserInfoRecordProto::unitattr_size() const {
  return unitattr_.size();
}
inline void UserInfoRecordProto::clear_unitattr() {
  unitattr_.Clear();
}
inline const ::BaseAttrProto& UserInfoRecordProto::unitattr(int index) const {
  return unitattr_.Get(index);
}
inline ::BaseAttrProto* UserInfoRecordProto::mutable_unitattr(int index) {
  return unitattr_.Mutable(index);
}
inline ::BaseAttrProto* UserInfoRecordProto::add_unitattr() {
  return unitattr_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::BaseAttrProto >&
UserInfoRecordProto::unitattr() const {
  return unitattr_;
}
inline ::google::protobuf::RepeatedPtrField< ::BaseAttrProto >*
UserInfoRecordProto::mutable_unitattr() {
  return &unitattr_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::BaseAttrProto_ePart>() {
  return ::BaseAttrProto_ePart_descriptor();
}
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::BaseAttrProto_eQuality>() {
  return ::BaseAttrProto_eQuality_descriptor();
}
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::BaseAttrProto_eQualityRank>() {
  return ::BaseAttrProto_eQualityRank_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_UserInfoRecordProto_2eproto__INCLUDED
